// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { existsSync } from "node:fs";
import { resolve } from "node:path";
import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

const envFiles = [
  resolve(process.cwd(), "../.env"),
  resolve(process.cwd(), ".env"),
];

for (const envFile of envFiles) {
  if (existsSync(envFile)) {
    config({ path: envFile, override: false });
  }
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
